version: "3.8"
services:
  web:
    image: chedv001/sanic-auth
    command: python main.py
    ports:
      - "8000:8000"
    depends_on:
      - db
  liquibase:
    image: webdevops/liquibase
    command: /opt/liquibase/liquibase update
    volumes:
      - ./migrations:/liquibase/
    depends_on:
      - db
  db:
    image: postgres
    env_file: database.conf
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
    external: true